local loader = dofile("loader.lua")()
local T = loader("tests/test_runner")
local effect = loader("lib/status_effect")

T.describe("status_effect", function()
  T.it("fades paused boards and requests blinking", function()
    local e = effect.compute("", true, "classic", 0)
    T.eq(e.fade, 0.55)
    T.ok(e.blink)
  end)

  T.it("prioritizes terminal effects over pause", function()
    local over = effect.compute("game_over", true, "classic", 0)
    local won = effect.compute("won", true, "classic", 0)
    T.eq(over.fade, 0)
    T.eq(won.fade, 0)
    T.ok(over.blink and won.blink)
    T.not_ok(T.deep_eq(over.board_tint, won.board_tint))
  end)

  T.it("pulses terminal tint by palette and time", function()
    local initial = effect.compute("game_over", false, "classic", 0)
    local peak = effect.compute("game_over", false, "classic", math.pi / 6)
    local ocean = effect.compute("game_over", false, "ocean", 0)
    T.not_ok(T.deep_eq(initial.board_tint, peak.board_tint))
    T.not_ok(T.deep_eq(initial.board_tint, ocean.board_tint))
  end)

  T.it("has no effect during ordinary play", function()
    local classic = effect.compute("", false, "classic", 0)
    local ocean = effect.compute("", false, "ocean", 0)
    T.eq(classic.board_tint, nil)
    T.eq(ocean.board_tint, nil)
    T.eq(classic.fade, 0)
    T.not_ok(classic.blink)
  end)

  T.it("highlights the current victory tile", function()
    local e = effect.compute("", false, "classic", 0, {
      row = 1, col = 2, value = 11, remaining = 5,
    })
    T.eq(e.tile_effect.row, 0)
    T.eq(e.tile_effect.col, 1)
    T.not_ok(T.deep_eq(e.tile_effect.bg, { 255, 200, 60 }))
  end)
end)

T.summary_and_exit()
